version: '3'

services:
  es:
    image: "elasticsearch:6.8.8"
    ports:
     - "9200:9200"

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: franticmarble
    ports:
      - '3306:3306'
    expose:
      - '3306'

  rabbit:
    image: rabbitmq:3.7
    restart: always
    ports:
      - "5672:5672"
    expose:
      - "5672"
